server.port = 8888
spring.application.name=claim-detector

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.streams.application-id=insurance-claim-logic

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages = com.insurance.claim_detector.model

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# The name of the queue your Go app will listen to
insurance.email.queue=q.claim-email

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG